name: Generated APK & AAB (Upload Artifacts)

env:
  main_project_module: app       
  playstore_name: Word Rush      

on:
  push:
    branches:
      - feature-branch                   
  workflow_dispatch:              

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

 
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

     
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

  
      - name: Run Gradle tests
        run: ./gradlew test

    
      - name: Build Gradle project
        run: ./gradlew build

      
      - name: Build APK Debug
        run: ./gradlew assembleDebug

      
      - name: Build APK Release
        run: ./gradlew assembleRelease

      
      - name: Build AAB Release
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

     
      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - AAB Release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
